name: Generate SDKs

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy SDK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code into VM
      uses: actions/checkout@v1
    - name: Deploy package
      uses: ./.github/actions/deploy
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
