name: Deploy Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.5
    - name: Build with dotnet
      run: dotnet build --configuration Release
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
